language: node_js
node_js:
  - 16.16.0
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - master
    - dev
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: 8c785842-c2c8-4053-9c4b-5fdac2012bf1
  app:
    master: node-hello-world-prod
    dev: node-hello-world-stagging
