language: node_js
node_js:
  - 16.16.0
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - master
    - dev
deploy:
  provider: heroku
  api_key:
    secure: 42af3af9-3126-4227-ad37-566d3cb0ff0a
  app:
    master: node-hello-world-prod
    dev: node-hello-world-stagging
